export const SENSOR_UPLOAD_INTERVAL_MS = 30_000;
export const SENSOR_OFFLINE_AFTER_MS = SENSOR_UPLOAD_INTERVAL_MS * 3;
export const SENSOR_STATUS_REFRESH_MS = 15_000;
export const SENSOR_READING_REFRESH_THROTTLE_MS = 5_000;
export const DEVICE_LIST_REFRESH_THROTTLE_MS = 5_000;
