export const memoryConfig = {
  historyHigh: 32,
  historyLow: 16,
  historyCharLimit: 10_000,
  rawScanTurns: 64,
  episodeSearchLimit: 3,
  understandingSearchLimit: 3,
  vectorCandidateLimit: 15,
  bm25CandidateLimit: 15,
  rerankTopN: 10,
  recencyHalfLifeDays: 7,
  relevanceWeight: 0.5,
  recencyWeight: 0.2,
  importanceWeight: 0.3,
  vectorRelevanceWeight: 0.75,
  bm25RelevanceWeight: 0.25,
  hybridSearchEnabled: true,
  closureDetectionTurnLimit: 32,
  closureDetectionMinNewTurns: 3,
  sessionClosureDelayMs: 30 * 60_000,
  queryTextLimit: 1800,
  bm25TextLimit: 700,
  understandingTextLimit: 1200,
  episodeTitleMaxChars: 80,
  episodeContentMaxChars: 120,
  understandingFieldMaxChars: 80,
  memoryKeywordMaxChars: 24
} as const;
