import { env } from "./env.js";

export const proactiveConfig = {
  enabled: env.PROACTIVE_ENABLED,
  llmEnabled: env.PROACTIVE_LLM_ENABLED,
  scanIntervalMs: env.PROACTIVE_SCAN_INTERVAL_MS,
  reminderMaxDays: env.PROACTIVE_REMINDER_MAX_DAYS,
  startupDelayMs: env.PROACTIVE_STARTUP_DELAY_MS,
  defaultTimezone: env.PROACTIVE_DEFAULT_TIMEZONE,
  quietStart: env.PROACTIVE_QUIET_START,
  quietEnd: env.PROACTIVE_QUIET_END,
  userPresenceWindowMs: env.PROACTIVE_USER_PRESENCE_WINDOW_MS,
  visibleHeartbeatTtlMs: env.PROACTIVE_VISIBLE_HEARTBEAT_TTL_MS,
  intentionClaimMs: env.PROACTIVE_INTENTION_CLAIM_MS,
  intentionKeepBaseCooldownMs: env.PROACTIVE_KEEP_BASE_COOLDOWN_MS,
  intentionKeepMaxCooldownMs: env.PROACTIVE_KEEP_MAX_COOLDOWN_MS,
  intentionFailureRetryBaseMs: env.PROACTIVE_INTENTION_FAILURE_RETRY_BASE_MS,
  intentionFailureRetryMaxMs: env.PROACTIVE_INTENTION_FAILURE_RETRY_MAX_MS,
  reminderClaimLeaseMs: env.PROACTIVE_REMINDER_CLAIM_LEASE_MS,
  reminderLateNarrativeMs: env.PROACTIVE_REMINDER_LATE_NARRATIVE_MS,
  reminderExpireAfterMs: env.PROACTIVE_REMINDER_EXPIRE_AFTER_MS,
  awayRetryMs: env.PROACTIVE_AWAY_RETRY_MS,
  budgetRetryMs: env.PROACTIVE_BUDGET_RETRY_MS,
  budgetRefillWindowMs: env.PROACTIVE_BUDGET_REFILL_WINDOW_MS,
  defaultTalkativeness: env.PROACTIVE_DEFAULT_TALKATIVENESS,
  budgetCapacity: {
    quiet: env.PROACTIVE_BUDGET_QUIET_CAPACITY,
    moderate: env.PROACTIVE_BUDGET_MODERATE_CAPACITY,
    active: env.PROACTIVE_BUDGET_ACTIVE_CAPACITY
  },
  bodyEwmaAlpha: env.PROACTIVE_BODY_EWMA_ALPHA,
  bodyPersistenceMs: env.PROACTIVE_BODY_PERSISTENCE_MS,
  bodyMaxGapMs: env.PROACTIVE_BODY_MAX_GAP_MS,
  bodyIntentionExpiryMs: env.PROACTIVE_BODY_INTENTION_EXPIRY_MS,
  silenceWarmDays: env.PROACTIVE_SILENCE_WARM_DAYS,
  silenceCoolDays: env.PROACTIVE_SILENCE_COOL_DAYS,
  silenceIntentionExpiryMs: env.PROACTIVE_SILENCE_INTENTION_EXPIRY_MS,
  anniversaryIntentionExpiryMs: env.PROACTIVE_ANNIVERSARY_INTENTION_EXPIRY_MS,
  morningGreetingEnabled: env.PROACTIVE_MORNING_GREETING_ENABLED,
  morningStart: env.PROACTIVE_MORNING_START,
  morningEnd: env.PROACTIVE_MORNING_END
};
